JD-Fuller/gameplan

- client/public/index.html
- client/src/store/index.js
- client/src/views/Boards.vue
- client/src/views/Login.vue
- server/main.js
> Registration and testing

- client/public/index.html
- server/controllers/EventController.js
- server/main.js
- server/models/Event.js
- server/services/AdminService.js
- server/services/BoardService.js
- server/services/EventService.js
Check the event routes and functions
> Server backend marcel

- server/controllers/RosterController.js
- server/main.js
- server/models/Roster.js
- server/services/RosterService.js
> Roster Service & Controller complete

- server/controllers/NoteController.js
- server/main.js
- server/models/Note.js
- server/services/NoteService.js
make sure it looks fine/ still going to test the requests
> Server notes marcel

- client/src/store/index.js
- client/src/views/Boards.vue
> Post method test

- client/src/store/index.js
- client/src/views/Event.vue
Able to add/delete Event - please verify and merge
> events render to event.vue

- client/src/store/index.js
- client/src/views/Event.vue
> removed debuggers

- client/src/views/Team.vue
> Small changes

- client/package-lock.json
- client/package.json
- client/src/NotificationService.js
- client/src/store/index.js
- client/src/views/Event.vue
- server/controllers/EventController.js
- server/services/EventService.js
> Modal for edit events

- client/src/views/Boards.vue
> popup for deleting a post works

- client/src/components/Nav.vue
- client/src/router/index.js
- client/src/views/Login.vue
- client/src/views/Register.vue
I know it looks trashy but I think tomorrow we can iron out the fine details. It has a solid functionality though. I just am having a difficult time trying to piece everything together. So if you see anything out of the ordinary. I am tracking that,
> Separate login reg

- client/package-lock.json
- client/package.json
- client/src/components/BoardNav.vue
- client/src/main.js
- client/src/views/Boards.vue
- client/src/views/Event.vue
- server/models/Event.js
> Add three events to boards view

- client/src/components/BoardNav.vue
- client/src/components/Player.vue
- client/src/store/index.js
- client/src/views/Team.vue
> Styling team client marcel

- client/src/components/BoardNav.vue
- client/src/components/Nav.vue
- client/src/components/Player.vue
- client/src/store/index.js
- client/src/views/Team.vue
- server/models/Player.js
- server/models/Team.js
Took away some of the containers and different spacing things to make the page space a little better
> got the players to add to the team

- client/src/NotificationService.js
- client/src/store/index.js
- client/src/views/Event.vue
- server/services/EventService.js
Now able to edit date for EVENTS
> added date to service for edits

- client/src/NotificationService.js
- client/src/views/Event.vue
> first commit, data stays on form

- client/src/components/BoardNav.vue
- client/src/components/Player.vue
- client/src/views/Team.vue
Changed styling. If we dont want it we can revert back
> Roster styling client marcel

- client/src/store/index.js
- server/controllers/EventController.js
- server/services/EventService.js
routing and events access and reset state
> Access user fan

- client/src/components/Nav.vue
- client/src/views/Login.vue
You likes?  Some sizing issues, but it works.
> video on login works, need to resize navbar

- client/src/views/Login.vue
check out the login page...still have to do registration
> login styling added

- client/src/components/BoardNav.vue
- client/src/store/index.js
- client/src/views/Boards.vue
- client/src/views/Event.vue
- client/src/views/Team.vue
- server/controllers/TeamController.js
- server/models/Player.js
- server/models/Post.js
- server/services/PlayerService.js
- server/services/PostService.js
Please review and merge when complete
> Get post by team id client jdmr
